version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      ./server
    image: server
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/group_enroll_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver    
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop

  client:
    build:
      ./client
    image: client
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - server

volumes:
  db_data:
    driver: local
